baseURL: http://example.org/
languageCode: en-us
title: Rajat Mhetre
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  homeInfoParams:
        Title: "Hi \U0001F44B"
        Content: My name is Rajat and I am working on building a future of data product for insurance software
  
  socialIcons:
        - name: twitter
          url: "https://twitter.com/mhetrerajat"
        - name: linkedin
          url: "https://www.linkedin.com/in/mhetrerajat"
        - name: github
          url: "https://github.com/mhetrerajat"